<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUhtDLs0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUhtDLs0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUhtDLs0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUhtDLs0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUhtDLs0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UhtDLs0',
    'container.build_id' => '6f72a268',
    'container.build_time' => 1773430374,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUhtDLs0');
